.TH JEDIT 1 "January 15, 2003"

.SH NAME
.B jedit
\- Programmer's text editor written in Java

.SH SYNOPSIS
.B "jedit "
[
.B options
] [
.B files
]

.SH DESCRIPTION
\fBjEdit\fP  is an Open Source, cross-platform text editor written in Java. It
has an extensive feature set that includes syntax highlighting, auto indent,
folding, word wrap, abbreviation expansion, multiple clipboards, powerful search
and replace, and much more.

Futhermore, jEdit is extremely customizable, and extensible, using either macros
written in the BeanShell scripting language, or plugins written in Java.

jEdit requires Java 2 version 1.3.

This manual page briefly documents the
.B jedit 
command. More documentation can be found by invoking the Help->jEdit Help
menu item within jEdit.
.PP

.SH OPTIONS

When opening files from the command line, a line number or marker to position 
the caret on can be specified like so:

$ jedit MyApplet.java +line:10
.TP
$ jedit thesis.tex +marker:c
.TP

The following switches are supported:

.TP
\fB\-background\fR
Runs jEdit in background mode. In background mode, the edit server will continue
listening for client connections even after all views are closed.
.TP
\fB\-nogui\fR
Makes jEdit not open an initial view, and instead only open one when the first 
client connects. Can only be used in combination with the -background switch. 
You can use this switch to "pre-load" jEdit when you log in to your computer, 
for example.
.TP
\fB\-norestore\fR
Disables automatic restore of previously open files on startup. This feature 
can also be set permanently in the Loading and Saving pane of the 
Utilities>Global Options dialog box.
.TP
\fB\-run=script\fR
Runs the specified BeanShell script. There can only be one of these parameters 
on the command line.
.TP
\fB\-server\fR
Stores the server port info in the file named "server" inside the settings 
directory.
.TP
\fB\-server=name\fR
Stores the server port info in the file named "name". File names for this 
parameter are relative to the settings directory.
.TP
\fB\-noserver\fR
Does not attempt to connect to a running edit server, and does not start one 
either.
.TP
\fB\-settings=dir\fR
Loads and saves the user-specific settings in the directory named "dir", instead
of the default $HOME/.jedit. The directory will be created automatically 
if it does not exist. Has no effect when connecting to another instance via 
the edit server.
.TP
\fB\-nosettings\fR
Starts jEdit without loading user-specific settings.
.TP
\fB\-noplugins\fR
Causes jEdit to not load any plugins.
.TP
\fB\-nostartupscripts\fR
Causes jEdit to not run any startup scripts. Has no effect when connecting to 
another instance via the edit server.
.TP
\fB\-usage\fR
Shows a brief command line usage message without starting jEdit. This message
 is also shown if an invalid switch was specified.
.TP
\fB\-version\fR
Shows the version number without starting jEdit.
.TP
\fB\--\fR
Specifies the end of the command line switches. Further parameters are treated
as file names, even if they begin with a dash. Can be used to open files whose 
names start with a dash, and so on.
.PP
To set minimum activity log level, specify a number as the first
command line parameter (1-9, 1 = print everything, 9 = fatal errors only).

.SH "SEE ALSO"
.BR java (1)

.SH VERSION
motor 4.1.0

.SH BUG REPORT
Report any bugs to slava@jedit.org.

.SH AUTHOR
This page is written by Krzysztof Krzyzaniak (eloy) <eloy@debian.org> for
Debian project.

.SH WEB
http://www.jedit.org/
